import Home from "./users/Home"
import Movies from "./users/Movies"
import Theaters from "./users/Theaters"
import Ticket from "./users/Ticket"
import Review from "./users/Review"
import Offer from "./users/Offer"
import Wallet from "./users/Wallet"
import Rewards from "./users/Rewards"
import Profile from "./users/Profile"
import TheaterDashboard from "./theater/Dashbroad"
import Login from "./auth/Login"
import SignUp from "./auth/Signup"
import ManageShowsPage from "./theater/MangeShows"
import SeatPricingPanel from "./theater/SeatPricingPanel"
import TheaterAdminSettings from "./theater/TheaterSetting"
import BookingsCancellationsPage from "./theater/BookingsCancellationsPage"
import TheaterAnalyticsDashboard from "./theater/TheaterAnalyticsDashboard"
import CustomerFeedbackPage from "./theater/CustomerFeedbackPage"
import OffersManagementPage from "./theater/Offers"

import AdminDashboard from "./admin/AdminHome"
import UserManagementPage from "./admin/UserManagement"
import TheaterManagementPage from "./admin/TheaterManagement"
import ContentModerationPage from "./admin/ContentModerationPage"
import AdminFinanceDashboard from "./admin/AdminFinanceDashboard"
import SystemAnalyticsPage from "./admin/SystemAnalyticsPage"
import SecurityAndComplianceDashboard from "./admin/SecurityAndComplianceDashboard"
import AdminSettingsPage from "./admin/AdminSettingsPage"

export { Home, Movies, Theaters, Ticket, Review, Offer, Wallet, Rewards, Profile, TheaterDashboard, Login, SignUp, ManageShowsPage, SeatPricingPanel, TheaterAdminSettings, BookingsCancellationsPage, TheaterAnalyticsDashboard, CustomerFeedbackPage, OffersManagementPage, AdminDashboard, UserManagementPage,TheaterManagementPage, ContentModerationPage, AdminFinanceDashboard, SystemAnalyticsPage, SecurityAndComplianceDashboard, AdminSettingsPage }
