export const API_BASE_URL = import.meta.env.VITE_APP_API_URL;
export const API_ADD_USER_URL = API_BASE_URL + import.meta.env.VITE_ADD_USER_URL;
export const API_UPDATE_USER_URL = API_BASE_URL + import.meta.env.VITE_UPDATE_USER_URL;
export const API_DELETE_USER_URL = API_BASE_URL + import.meta.env.VITE_DELETE_USER_URL;
export const API_GET_ALL_USERS_URL = API_BASE_URL + import.meta.env.VITE_GET_ALL_USERS_URL;
export const API_GET_THEATER_OWNERS_URL = API_BASE_URL + import.meta.env.VITE_GET_ALL_THEATER_OWNERS_URL;
export const API_GET_USER_BY_ID_URL = API_BASE_URL + import.meta.env.VITE_GET_USER_BY_ID_URL;

export const API_LOGIN_URL = API_BASE_URL + import.meta.env.VITE_LOGIN_URL;
export const API_SIGNUP_URL = API_BASE_URL + import.meta.env.VITE_SIGNUP_URL;

export const API_GET_ALL_THEATERS_URL = API_BASE_URL + import.meta.env.VITE_GET_ALL_THEATERS_URL;
export const API_GET_THEATER_BY_ID_URL = API_BASE_URL + import.meta.env.VITE_GET_THEATER_BY_ID_URL;
export const API_ADD_THEATER_URL = API_BASE_URL + import.meta.env.VITE_CREATE_THEATER_URL;
export const API_UPDATE_THEATER_URL = API_BASE_URL + import.meta.env.VITE_UPDATE_THEATER_URL;
export const API_DELETE_THEATER_URL = API_BASE_URL + import.meta.env.VITE_DELETE_THEATER_URL;
export const API_CREATE_THEATER_SCREEN_URL = API_BASE_URL + import.meta.env.VITE_CREATE_THEATER_SCREEN_URL
export const API_GET_ALL_THEATER_SCREENS_URL = API_BASE_URL + import.meta.env.VITE_GET_ALL_THEATER_SCREENS_URL
export const API_UPDATE_THEATER_SCREEN_URL = API_BASE_URL + import.meta.env.VITE_UPDATE_THEATER_SCREEN_BY_ID_URL
export const API_DELETE_THEATER_SCREEN_URL = API_BASE_URL + import.meta.env.VITE_DELETE_THEATER_SCREEN_BY_ID_URL

